<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="vikas_195" ignored="4" name="Test" tests="3" failures="1" timestamp="07 Jul 2019 23:13:02 GMT" time="21.337" errors="0">
  <testcase name="test1" time="0.013" classname="com.ActiTime.TestScripts.TestingFailureTest">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at com.ActiTime.TestScripts.TestingFailureTest.test1(TestingFailureTest.java:15)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase name="validateNewTask" time="2.237" classname="com.ActiTime.TestScripts.ValidateCreateNewTaskTest"/>
  <testcase name="createNewCustomer" time="3.398" classname="com.ActiTime.TestScripts.CreateNewUserTest"/>
  <testcase name="@AfterSuite closeSuit" time="0.0" classname="com.ActiTime.GenericLib.BaseClass">
    <ignored/>
  </testcase> <!-- @AfterSuite closeSuit -->
  <testcase name="@AfterSuite closeSuit" time="0.0" classname="com.ActiTime.GenericLib.BaseClass">
    <ignored/>
  </testcase> <!-- @AfterSuite closeSuit -->
  <testcase name="@BeforeSuite databaseRunning" time="0.0" classname="com.ActiTime.GenericLib.BaseClass">
    <ignored/>
  </testcase> <!-- @BeforeSuite databaseRunning -->
  <testcase name="@BeforeSuite databaseRunning" time="0.0" classname="com.ActiTime.GenericLib.BaseClass">
    <ignored/>
  </testcase> <!-- @BeforeSuite databaseRunning -->
</testsuite> <!-- Test -->
